blogapp/urls.py
from django.urls import path
from .views import *

app_name = "blogapp"


urlpatterns = [
	
	path("login/", LoginView.as_view(), name = "login"),
	path("logout/", LogoutView.as_view(), name = "logout"),
	path("signup/", SignupView.as_view(), name = "signup"),

	path("", BlogHomeView.as_view(), name = "bloghome"),
	path("list/", BlogListView.as_view(), name = "bloglist"),
	path("detail/<int:pk>/", BlogDetailView.as_view(), name = "blogdetail"),
	path("create/", BlogCreateView.as_view(), name = "blogcreate"),
	path("update/<int:pk>/", BlogUpdateView.as_view(), name = "blogupdate"),
	path("delete/<int:pk>/", BlogDeleteView.as_view(), name = "blogdelete"),
	path("manage/", BlogManageView.as_view(), name = "blogmanage"),
		
]

diaryapp/urls.py
from django.urls import path
from .views import *

app_name = "diaryapp"


urlpatterns = [
	path("", DiaryHomeView.as_view(), name = "diaryhome"),
]

pharmacyapp/urls.py
from django.urls import path
from .views import *

app_name = "pharmacyapp"

urlpatterns = [

# Admin URLS
	path("pharmacy-admin/", AdminHomeView.as_view(), name = "adminhome" ),
	path("pharmacy-admin/medicine/list/", AdminMedicineListView.as_view(), 
		name = "adminmedicinelist"),
	path("pharmacy-admin/medicine/<int:pk>/detail/", AdminMedicineDetailView.as_view(), 
		name = "adminmedicinedetail"),
	path("pharmacy-admin/single-medicine/<int:pk>/detail/", AdminSingleMedicineDetailView.as_view(), 
		name = "adminsinglemedicinedetail"),

	path("pharmacy-admin/batch/list/", AdminBatchListView.as_view(), 
		name = "adminbatchlist"),

	path("pharmacy-admin/company/list/", AdminCompanyListView.as_view(), 
		name = "admincompanylist"),
	path("pharmacy-admin/supplier/list/", AdminSupplierListView.as_view(), 
		name = "adminsupplierlist"),




# Client URLS

	path("", HomeView.as_view(), name = 'home' ),



]

pharmacyproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pharmacyapp.urls')),
    path('diary/', include('diaryapp.urls')),
    path('blog/', include('blogapp.urls')),
    

]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/blogtemplates/blogbase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href=" {% static 'adminstatic/css/style.css' %} ">

	<link rel="icon" href=" {% static 'adminstatic/images/s-icon.jpg' %} " sizes="96x96" >
	<script src="https://kit.fontawesome.com/469736bb45.js" crossorigin="anonymous"></script>

	<script src=" {% static 'adminstatic/js/jquery-3.4.1.min.js' %} " ></script>
	<script src=" {% static 'adminstatic/js/bootstrap.min.js' %} "></script>
	<link rel="stylesheet" type="text/css" href=" {% static 'adminstatic/css/bootstrap.min.css' %} ">

	{% block css %}
	{% endblock %}

	<link rel="stylesheet" href=" {% static 'adminstatic/css/jquery.toast.min.css' %} ">


	{% block js %}
	{% endblock %}

</head>
<body class="container-fluid" id="body">

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href=" {% url 'pharmacyapp:adminhome' %} ">Welcome-P</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href=" {% url 'pharmacyapp:adminhome' %} ">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href=" {% url 'pharmacyapp:adminmedicinelist' %} ">Medicines</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Purchase</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Sales</a>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          My Journal
	        </a>
	        <div class="dropdown-menu navbar-dark bg-dark" aria-labelledby="navbarDropdown">
	          <a id="navbar-dropdown" class="dropdown-item" href=" {% url 'diaryapp:diaryhome' %} " style="color: green;">Diary</a>
	          <a id="navbar-dropdown" class="dropdown-item" href=" {% url 'blogapp:bloghome' %} " style="color: green;">Blogs</a>
	          <div class="dropdown-divider"></div>
	          <a id="navbar-dropdown" class="dropdown-item" href="#" style="color: green;">To-Do-Lists</a>
	        </div>
	      </li>
	      {% if request.user.is_authenticated %}
	      <li class="nav-item">
	        <a class="nav-link disabled" href="#" style="color: #03AC13;">User: {{request.user}}</a>
	      </li>
	      {% else %}
	      <!-- <li class="nav-item">
	      	<a class="nav-link" href=" {% url 'blogapp:login' %} ">Signin</a>
	      </li>
	      <li class="nav-item">
	      	<a class="nav-link" href=" {% url 'blogapp:signup' %} ">Signup</a>
	      </li> -->
	      {% endif %}
	    </ul>
	    <form class="form-inline my-2 my-lg-0">
	      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	    </form>
	  </div>
	</nav>

	

	{% block content %}
	{% endblock %}

	<div id="footer" >
		<h4>Created By: Handsome </h4>
		
	</div>

	<script type="text/javascript" src=" {% static 'adminstatic/js/jquery.toast.min.js' %} "></script>


<script type="text/javascript">
   $(".subform1").on("submit",function(e){
      e.preventDefault();
      $this = $(this);
      $.ajax({
         type:"POST",
         url: $this.attr('action'),
         data: $this.serialize(),
         success : function(data){
            if (data.success){
                $.toast({
                    heading: 'Login Prompt',
                    text: data.success,
                    bgColor: 'green',
                    position: 'top-right',
                    showHideTransition: 'slide',
                    icon: 'success'
                });
                 $this.trigger("reset");
            }
            else {
              $.toast({
                    heading: 'Login Prompt',
                    text: data.error,
                    bgColor: 'red',
                    position: 'top-right',
                    showHideTransition: 'slide',
                    icon: 'warning'
                });
              $this.trigger("reset");
           }
         }
      });
   });
</script>


<script type="text/javascript">
   '{% if messages %}'
      '{% for message in messages %}'
         $.toast({
                 heading: 'News Flash',
                 text: '{{message}}',
                 bgColor: 'red',
                 position: 'top-right',
                 showHideTransition: 'slide',
                 icon: 'warning'
                });
      '{% endfor %}'
   '{% endif %}'
</script>




<script type="text/javascript">
	$(document).ready(function() {
	    $(".dropdownMenuLink").dropdown();
	});
</script>

</body>
</html>

templates/blogtemplates/blogcreate.html
{% extends 'blogtemplates/blogminbase.html' %}
{% load static %}

{% block title %}
Blog Create Page
{% endblock %}

{% block content %}

<div class="row">
	<div class="col" style="text-align: center;">
		<br>
		<h5 style="border: 1px solid #444; font-size: 1.5em;">=========Create New Blog========</h5>
	</div>
</div>

<div class="row mt-5">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<h4 style="text-align: center; background-color: lightgreen;">Blog Create Form</h4>
		<form method="post" enctype="multipart/form-data" style="border: 2px solid #897; padding: 5px;" class="subform1">
			{% csrf_token %}
			{{form.as_p}}
			<div>
				<input type="submit" name="submit" value="Create" id="blogcreate">
			</div>
		</form>
	</div>
	<div class="col-md-3"></div>
</div>



{% endblock %}

templates/blogtemplates/blogdelete.html
{% extends 'blogtemplates/blogminbase.html' %}
{% load static %}

{% block title %}
Blog Delete Page
{% endblock %}

{% block content %}

<div class="row mt-2 ml-2">
	<div class="col" style="text-align: center; margin-bottom: 19px;">
		<form method="POST">
			{% csrf_token %}
			<h4>Do You Want To Delete This Blog???</h4>
			<h4>Title: {{blog.title}}</h4>
			<button class="btn btn-danger">YES</button>
			<a href=" {% url 'blogapp:bloglist' %} " class="btn btn-info">Never Mind</a>
		</form>
	</div>
</div>

{% endblock %}

templates/blogtemplates/blogdetail.html
{% extends 'blogtemplates/blogminbase.html' %}
{% load static %}

{% block title %}
Blog Detail Page
{% endblock %}

{% block content %}
<div class="row" id="blogging">
	<div class="col" id="blogging">
		<h3>Blog Title: {{blogobject.title}}</h3>
	</div>
</div>

<div class="row mt-1" id="blogging-body">
	<div class="col-6">
		<img src=" {{blogobject.image.url}} " style="width: 100%; height: mx-auto;">		
	</div>
	<div class="col-6" style="background-color: #6CBB3C;">
		<h5>Description: </h5>
		<p>{{blogobject.description}}</p>
		<br>
		<h4>Author: {{blogobject.author}}</h4>
		<h4>Created At: {{blogobject.created_at|date}}</h4>
	</div>
</div>

<div class="row" id = "blogging">
	<div class="col-md-6" style="text-align: center; color: silver;">
		<h5>View Count: {{blogobject.blog_views}}</h5>
	</div>
	<div class="col-md-6" style="text-align: center;">
		<a href=" {% url 'blogapp:blogupdate' blogobject.id %} " class="btn btn-warning" style="margin: 5px 2px;">Update</a>
		<a href=" {% url 'blogapp:blogdelete' blogobject.id %} " class="btn btn-danger" style="margin: 5px 2px;">Delete</a>
	</div>
</div>


{% endblock %}

templates/blogtemplates/bloghome.html
{% extends 'blogtemplates/blogbase.html' %}
{% load static %}

{% block title %}
Blog Home Page
{% endblock %}

{% block content %}

	<div class="row" style="margin-top: 5px; margin-right: 1px;" id="container">
		<div class="col-md-4">
			<img src=" {% static 'adminstatic/images/green.jpg' %} " alt="Snow" style="width:100%; height: mx-auto;">
			<div class="center"><a href=" {% url 'blogapp:bloglist' %} " class="btn btn-primary" style="opacity: 70%; font-size: 1.5em;">All Blogs</a></div>
		</div>
		<div class="col-md-4">
			<img src=" {% static 'adminstatic/images/green.jpg' %} " alt="Snow" style="width:100%; height: mx-auto;">
			<div class="center"><a href=" {% url 'blogapp:blogcreate' %} " class="btn btn-success" style="opacity: 70%; font-size: 1.5em;">Create Blogs</a></div>
		</div>
		<div class="col-md-4">
			<img src=" {% static 'adminstatic/images/green.jpg' %} " alt="Snow" style="width:100%; height: mx-auto;">
			<div class="center"><a href=" {% url 'blogapp:blogmanage' %} " class="btn btn-danger" style="opacity: 70%; font-size: 1.5em;">Manage Blogs</a></div>
		</div>
	</div>


	<div class="row" style="margin-top: 5px; margin-right: 1px;" id="container">
		<div class="col-md-2"></div>
		<div class="col-md-4">
			{% if request.user.is_authenticated %}
			<img src=" {% static 'adminstatic/images/green.jpg' %} " alt="Snow" style="width:100%; height: mx-auto;">
			<div class="center"><a href="#" class="btn btn-danger" style="opacity: 70%; font-size: 1.5em; text-transform: uppercase;">"<i class="fas fa-grin-hearts"></i>"{{request.user}}"<i class="fas fa-grin-hearts"></i>"</a></div>
			{% else %}
			<img src=" {% static 'adminstatic/images/green.jpg' %} " alt="Snow" style="width:100%; height: mx-auto;">
			<div class="center"><a href=" {% url 'blogapp:login' %} " class="btn btn-danger" style="opacity: 70%; font-size: 1.5em;">SignIn</a></div>
			{% endif %}
		</div>
		<div class="col-md-4">
			{% if request.user.is_authenticated %}
			<img src=" {% static 'adminstatic/images/green.jpg' %} " alt="Snow" style="width:100%; height: mx-auto;">
			<div class="center"><a href=" {% url 'blogapp:logout' %} " class="btn btn-warning" style="opacity: 70%; font-size: 1.5em;">"<i class="far fa-dizzy"></i>"Signout"<i class="far fa-dizzy"></i>"</a></div>
			{% else %}
			<img src=" {% static 'adminstatic/images/green.jpg' %} " alt="Snow" style="width:100%; height: mx-auto;">
			<div class="center"><a href=" {% url 'blogapp:signup' %} " class="btn btn-warning" style="opacity: 70%; font-size: 1.5em;">"<i class="far fa-grin-tongue-squint"></i>"Signup"<i class="far fa-grin-tongue-squint"></i>"</a></div>
			{% endif %}
		</div>
		<div class="col-md-2"></div>
	</div>

{% endblock %}

templates/blogtemplates/bloglist.html
{% extends 'blogtemplates/blogminbase.html' %}
{% load static %}

{% block title %}
Blog List 
{% endblock %}

{% block content %}

	
	<div class="row" style="margin-top: 5px;">
		<div class="col-md-6">
			<a href="" class="btn btn-primary">Filter</a>			
		</div>
		<div class="col-md-6" style="text-align: right;">
			<a href="" class="btn btn-warning">Filter</a>			
		</div>
	</div>

	<div class="row ml-1" style="background-color: #25A032;">
		<h4>All Blogs Availables</h4>
	</div>
	<div class="row ml-1">
		<div class="col-md-9">
			<div class="row" style="background-color: #248823;">
				{% for blog in allblogs %}
				<div class="col-md-4">
					<a href=" {% url 'blogapp:blogdetail' blog.id %} "><h4>{{blog.title|truncatechars:20}}</h4></a>
					<h4>Written by: {{blog.author}}</h4>
					<img src="{{blog.image.url}}" style="width: 100%; height: mx-auto;">
					<h4>{{blog.description|truncatewords:15}} <a href=" {% url 'blogapp:blogdetail' blog.id %} " style="color: orange;">See More...</a></h4>
				</div>
				{% endfor %}
			</div>

			{% if page_obj.has_other_pages %}
			<ul class="pagination mt-2">
			    {% if page_obj.has_previous %}
			    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
			    {% else %}
			    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
			    {% endif %}
			    {% for n in page_obj.paginator.page_range %}
			        {% if page_obj.number == n %}
			            <li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
			        {% else %}
			            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{n}}</a></li>
			        {% endif %}
			    {% endfor %}
			    {% if page_obj.has_next %}
			      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number}}">Next</a></li>
			    {% else %}
			      <li class="page-item disabled"><span class="page-link">Next</span></li>
			    {% endif %}
			</ul>
			{% endif %}

		</div>
		<div class="col-md-3">
			<div class="row">
				<div class="col">
					<h4 style="text-align: center; color: purple;">Most Watched Blogs</h4><hr>
				</div>
			</div>
			<div class="row mt-2">
				<div class="col-md">
					{% for mblog in mostwatchblogs|slice:"3" %}
					<a href=" {% url 'blogapp:blogdetail' mblog.id %} "><img src="{{mblog.image.url}}" style="width: 100%; height: mx-auto;">
					<h5 style="text-align: center;">{{mblog.title}}</h5>
					</a>
					<hr>
					{% endfor %}
				</div>
			</div>
		</div>

	</div>
			

{% endblock %}

templates/blogtemplates/blogmanage.html
{% extends "blogtemplates/blogminbase.html" %}
{% load static %}

{% block title %}
Manage Blog
{% endblock %}

{% block content %}

	<div class="row mt-2 ml-1 mr-1">
		<div class="col" style="text-align: center; background-color: grey;">
			<h5>List Of All Blogs</h5>
		</div>
	</div>
	
		
	<div class="row mt-2">
		<div class="col-md-1">

		</div>
		<div class="col-md-10">
			<table class="table">
				<thead>
					<tr class="table-heading">
						<th>SN</th>
						<th>Title</th>
						<th>Image</th>
						<th>Short Description</th>
						<th>Author</th>
						<th>Created-Date</th>
						<th>Total Views</th>
						<th>Manage</th>
					</tr>
				</thead>
				<tbody>
					{% for blog in allblogs %}
					<tr class="table-blog">
						<td>{{forloop.counter}}</td>
						<td>{{blog.title}}</td>
						<td><img src="{{blog.image.url}}" style="width: 100%; height: mx-auto;"></td>
						<td>{{blog.description|truncatewords:"8"}}</td>
						<td>{{blog.author}}</td>
						<td>{{blog.created_at}}</td>
						<td>{{blog.blog_views}}</td>
						<td>
							<a href=" {% url 'blogapp:blogupdate' blog.id %} " class="btn btn-primary"><i class="fas fa-edit"></i></a>
							<br>
							<a href=" {% url 'blogapp:blogdelete' blog.id %} " class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="col-md-1"></div>
	</div>


	<div class="row ml-1 mr-1">
		<div class="col-md-1"></div>
		<div class="col-md-10">
			<!-- Top Pagination Start -->
                {% if allblogs.has_other_pages %}
                <ul class="pagination">
                    {% if allblogs.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ allblogs.previous_page_number }}">Previous</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                    {% endif %}
                    {% for n in allblogs.paginator.page_range %}
                        {% if allblogs.number == n %}
                            <li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{n}}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if allblogs.has_next %}
                      <li class="page-item"><a class="page-link" href="?page={{ allblogs.next_page_number}}">Next</a></li>
                    {% else %}
                      <li class="page-item disabled"><span class="page-link">Next</span></li>
                    {% endif %}
                </ul>
                {% endif %}
                <!-- Top Pagination Ends -->
        </div>
        <div class="col-md-1"></div>
    </div>


{% endblock %}

templates/blogtemplates/blogminbase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href=" {% static 'adminstatic/css/style.css' %} ">

	<link rel="icon" href=" {% static 'adminstatic/images/s-icon.jpg' %} " sizes="96x96" >
	<script src="https://kit.fontawesome.com/469736bb45.js" crossorigin="anonymous"></script>

	<script src=" {% static 'adminstatic/js/jquery-3.4.1.min.js' %} " ></script>
	<script src=" {% static 'adminstatic/js/bootstrap.min.js' %} "></script>
	<link rel="stylesheet" type="text/css" href=" {% static 'adminstatic/css/bootstrap.min.css' %} ">

	{% block css %}
	{% endblock %}


	<link rel="stylesheet" href=" {% static 'adminstatic/css/jquery.toast.min.css' %} ">

	{% block js %}
	{% endblock %}

</head>
<body class="container-fluid" id="body">

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href=" {% url 'pharmacyapp:adminhome' %} ">Welcome-P</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href=" {% url 'pharmacyapp:adminhome' %} ">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href=" {% url 'pharmacyapp:adminmedicinelist' %} ">Medicines</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Purchase</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Sales</a>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          My Journal
	        </a>
	        <div class="dropdown-menu navbar-dark bg-dark" aria-labelledby="navbarDropdown">
	          <a id="navbar-dropdown" class="dropdown-item" href=" {% url 'diaryapp:diaryhome' %} " style="color: green;">Diary</a>
	          <a id="navbar-dropdown" class="dropdown-item" href=" {% url 'blogapp:bloghome' %} " style="color: green;">Blogs</a>
	          <div class="dropdown-divider"></div>
	          <a id="navbar-dropdown" class="dropdown-item" href="#" style="color: green;">To-Do-Lists</a>
	        </div>
	      </li>
	      {% if request.user.is_authenticated %}
	      <li class="nav-item">
	        <a class="nav-link disabled" href="#" style="color: #03AC13;">User: {{request.user}}</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href=" {% url 'blogapp:logout' %} " style="color: red;">Signout</a>
	      </li>
	      
	      {% else %}
	     <!--  <li class="nav-item">
	      	<a class="nav-link" href=" {% url 'blogapp:login' %} ">Signin</a>
	      </li>
	      <li class="nav-item">
	      	<a class="nav-link" href=" {% url 'blogapp:signup' %} ">Signup</a>
	      </li> -->
	      {% endif %}
	      <li class="nav-item">
	      	<a href=" {% url 'blogapp:bloghome' %} " class="btn btn-primary"><i class="fas fa-home"> Blog</i></a>
	      </li>
	    </ul>
	    <form class="form-inline my-2 my-lg-0">
	      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	    </form>
	  </div>
	</nav>

	<div class="row" style="margin-top: 5px;" id="container">
		<div class="col-md-4">
			<img src=" {% static 'adminstatic/images/green.jpg' %} " alt="Snow" style="width:100%; height: 60px;">
			<div class="center"><a href=" {% url 'blogapp:bloglist' %} " class="btn btn-primary" style="opacity: 70%; font-size: 1.5em;">All Blogs</a></div>
		</div>
		<div class="col-md-4">
			<img src=" {% static 'adminstatic/images/green.jpg' %} " alt="Snow" style="width:100%; height: 60px;">
			<div class="center"><a href=" {% url 'blogapp:blogcreate' %} " class="btn btn-success" style="opacity: 70%; font-size: 1.5em;">Create Blogs</a></div>
		</div>
		<div class="col-md-4">
			<img src=" {% static 'adminstatic/images/green.jpg' %} " alt="Snow" style="width:100%; height: 60px;">
			<div class="center"><a href=" {% url 'blogapp:blogmanage' %} " class="btn btn-danger" style="opacity: 70%; font-size: 1.5em;">Manage Blogs</a></div>
		</div>
	</div>

	

	{% block content %}
	{% endblock %}

	<div id="footer" >
		<h4>Created By: Handsome </h4>
		
	</div>

	<script type="text/javascript" src=" {% static 'adminstatic/js/jquery.toast.min.js' %} "></script>


<script type="text/javascript">
   $(".subform1").on("submit",function(e){
      e.preventDefault();
      $this = $(this);
      $.ajax({
         type:"POST",
         url: $this.attr('action'),
         data: $this.serialize(),
         success : function(data){
            if (data.success){
                $.toast({
                    heading: 'Login Success',
                    text: data.success,
                    bgColor: 'green',
                    position: 'top-right',
                    showHideTransition: 'slide',
                    icon: 'success'
                });
                 $this.trigger("reset");
            }
            else {
              $.toast({
                    heading: 'Login Error',
                    text: data.error,
                    bgColor: 'red',
                    position: 'top-right',
                    showHideTransition: 'slide',
                    icon: 'warning'
                });
              $this.trigger("reset");
           }
         }
      });
   });
</script>


<script type="text/javascript">
   '{% if messages %}'
      '{% for message in messages %}'
         $.toast({
                 heading: 'Login Prompt',
                 text: '{{message}}',
                 bgColor: 'red',
                 position: 'top-right',
                 showHideTransition: 'slide',
                 icon: 'warning'
                });
      '{% endfor %}'
   '{% endif %}'
</script>




<script type="text/javascript">
	$(document).ready(function() {
	    $(".dropdownMenuLink").dropdown();
	});
</script>

</body>
</html>

templates/blogtemplates/blogupdate.html
{% extends 'blogtemplates/blogminbase.html' %}
{% load static %}

{% block title %}
Blog Update Page
{% endblock %}

{% block content %}

<div class="row">
	<div class="col" style="text-align: center;">
		<br>
		<h5 style="border: 1px solid #444; font-size: 1.5em;">=========Update Blog========</h5>
	</div>
</div>

<div class="row mt-5">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<h4 style="text-align: center; background-color: lightgreen;">Blog Update Form</h4>
		<form method="post" enctype="multipart/form-data" style="border: 2px solid #897; padding: 5px;">
			{% csrf_token %}
			{{form.as_p}}
			<div>
				<input type="submit" name="submit" value="Update" id="blogcreate">
				<input type="submit" name="submit" value="Cancel" id="blogcancel">
			</div>
		</form>
	</div>
	<div class="col-md-3"></div>
</div>



{% endblock %}