blogapp/urls.py
from django.urls import path
from .views import *

app_name = "blogapp"


urlpatterns = [
	
	path("login/", LoginView.as_view(), name = "login"),
	path("logout/", LogoutView.as_view(), name = "logout"),
	path("signup/", SignupView.as_view(), name = "signup"),

	path("", BlogHomeView.as_view(), name = "bloghome"),
	path("list/", BlogListView.as_view(), name = "bloglist"),
	path("detail/<int:pk>/", BlogDetailView.as_view(), name = "blogdetail"),
	path("create/", BlogCreateView.as_view(), name = "blogcreate"),
	path("update/<int:pk>/", BlogUpdateView.as_view(), name = "blogupdate"),
	path("delete/<int:pk>/", BlogDeleteView.as_view(), name = "blogdelete"),
	path("manage/", BlogManageView.as_view(), name = "blogmanage"),
		
]

diaryapp/urls.py
from django.urls import path
from .views import *

app_name = "diaryapp"


urlpatterns = [
	path("", DiaryHomeView.as_view(), name = "diaryhome"),
]

pharmacyapp/urls.py
from django.urls import path
from .views import *

app_name = "pharmacyapp"

urlpatterns = [

# Admin URLS
	path("pharmacy-admin/", AdminHomeView.as_view(), name = "adminhome" ),
	path("pharmacy-admin/medicine/list/", AdminMedicineListView.as_view(), 
		name = "adminmedicinelist"),
	path("pharmacy-admin/medicine/<int:pk>/detail/", AdminMedicineDetailView.as_view(), 
		name = "adminmedicinedetail"),
	path("pharmacy-admin/single-medicine/<int:pk>/detail/", AdminSingleMedicineDetailView.as_view(), 
		name = "adminsinglemedicinedetail"),

	path("pharmacy-admin/batch/list/", AdminBatchListView.as_view(), 
		name = "adminbatchlist"),

	path("pharmacy-admin/company/list/", AdminCompanyListView.as_view(), 
		name = "admincompanylist"),
	path("pharmacy-admin/supplier/list/", AdminSupplierListView.as_view(), 
		name = "adminsupplierlist"),




# Client URLS

	path("", HomeView.as_view(), name = 'home' ),



]

pharmacyproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pharmacyapp.urls')),
    path('diary/', include('diaryapp.urls')),
    path('blog/', include('blogapp.urls')),
    

]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/admintemplates/adminbase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href=" {% static 'adminstatic/css/style.css' %} ">

	<link rel="icon" href=" {% static 'adminstatic/images/s-icon.jpg' %} " sizes="96x96" >
	<script src="https://kit.fontawesome.com/469736bb45.js" crossorigin="anonymous"></script>

	<script src=" {% static 'adminstatic/js/jquery-3.4.1.min.js' %} " ></script>
	<script src=" {% static 'adminstatic/js/bootstrap.min.js' %} "></script>
	<link rel="stylesheet" type="text/css" href=" {% static 'adminstatic/css/bootstrap.min.css' %} ">

	{% block css %}
	{% endblock %}

	<link rel="stylesheet" href=" {% static 'adminstatic/css/jquery.toast.min.css' %} ">

	{% block js %}
	{% endblock %}

</head>
<body class="container-fluid" id="body">

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href=" {% url 'pharmacyapp:adminhome' %} ">Welcome-P</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href=" {% url 'pharmacyapp:adminhome' %} ">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href=" {% url 'pharmacyapp:adminmedicinelist' %} ">Medicines</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Purchase</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Sales</a>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          My Journal
	        </a>
	        <div class="dropdown-menu navbar-dark bg-dark" aria-labelledby="navbarDropdown">
	          <a id="navbar-dropdown" class="dropdown-item" href=" {% url 'diaryapp:diaryhome' %} " style="color: green;">Diary</a>
	          <a id="navbar-dropdown" class="dropdown-item" href=" {% url 'blogapp:bloghome' %} " style="color: green;">Blogs</a>
	          <div class="dropdown-divider"></div>
	          <a id="navbar-dropdown" class="dropdown-item" href="#" style="color: green;">To-Do-Lists</a>
	        </div>
	      </li>
	      {% if request.user.is_authenticated %}
	      <li class="nav-item">
	        <a class="nav-link disabled" href="#" style="color: #03AC13;">User: {{request.user}}</a>
	      </li>
	      <li class="nav-item">
	      	<a class="nav-link" href=" {% url 'blogapp:logout' %} " style="color: red;">Signout</a>
	      </li>
	      {% else %}
<!-- 	      <li class="nav-item">
	      	<a class="nav-link" href=" {% url 'blogapp:login' %} ">Signin</a>
	      </li>
	      <li class="nav-item">
	      	<a class="nav-link" href=" {% url 'blogapp:signup' %} ">Signup</a>
	      </li> -->
	      {% endif %}
	    </ul>
	    <form class="form-inline my-2 my-lg-0">
	      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	    </form>
	  </div>
	</nav>

	{% block content %}
	{% endblock %}

	<div id="footer" >
		<h4>Created By: Handsome </h4>
		
	</div>


	<script type="text/javascript" src=" {% static 'adminstatic/js/jquery.toast.min.js' %} "></script>


<script type="text/javascript">
   $(".subform1").on("submit",function(e){
      e.preventDefault();
      $this = $(this);
      $.ajax({
         type:"POST",
         url: $this.attr('action'),
         data: $this.serialize(),
         success : function(data){
            if (data.success){
                $.toast({
                    heading: 'Login Success',
                    text: data.success,
                    bgColor: 'green',
                    position: 'top-right',
                    showHideTransition: 'slide',
                    icon: 'success'
                });
                 $this.trigger("reset");
            }
            else {
              $.toast({
                    heading: 'Login Error',
                    text: data.error,
                    bgColor: 'red',
                    position: 'top-right',
                    showHideTransition: 'slide',
                    icon: 'warning'
                });
              $this.trigger("reset");
           }
         }
      });
   });
</script>


<script type="text/javascript">
   '{% if messages %}'
      '{% for message in messages %}'
         $.toast({
                 heading: 'Login Prompt',
                 text: '{{message}}',
                 bgColor: 'red',
                 position: 'top-right',
                 showHideTransition: 'slide',
                 icon: 'warning'
                });
      '{% endfor %}'
   '{% endif %}'
</script>



<script type="text/javascript">
	$(document).ready(function() {
	    $(".dropdownMenuLink").dropdown();
	});
</script>

<script type="text/javascript">
    jQuery(document).ready(function($) {
        $(".clickable-row").click(function() {
            window.location = $(this).attr("data-href");
        });
    });
</script>

</body>
</html>

templates/admintemplates/adminbatchlist.html
{% extends 'admintemplates/adminmedicalbase.html' %}
{% load static %}

{% block title %}
Batch List Page
{% endblock %}

{% block content %}

<div class="row mt-1 ml-1 mr-1">
	<div class="col" style="background-color: lightgreen; text-align: center;">
		<h4>Batch List</h4>
	</div>
</div>

<div class="row mt-1">
	<div class="col-md-9">
		
		<div class="row ml-1 mt-1 mr-1">
			<div class="col" style="text-align: center; color: white; background-color: grey;">
				<h4>Table of Batches</h4>
			</div>
		</div>
		<div class="row mt-1">
			<div class="col-md ml-1">
				<table class="container-fluid">
					<thead>
						<tr>
							<th>SN</th>
							<th>Name</th>
							<th>Manufacturer</th>
							<th>Supplier</th>
							<th>Manufacture Date</th>
							<th>Expire Date</th>
							<th>Time Left</th>
							<th>Manage</th>
						</tr>
					</thead>
					<tbody>
						{% for batch in allbatch %}
						<tr class="table-blog clickable-row" data-href = " {% url 'pharmacyapp:adminmedicinedetail' batch.id %} ">
							<td>{{forloop.counter}}</td>
							<td>{{batch.name}}</td>
							<td>{{batch.manufacturer}}</td>
							<td>{{batch.supplier.name}}</td>
							<td>{{batch.manufacture_date}}</td>
							<td>{{batch.expire_date}}</td>
							<td><span><h5>{{batch.expire_date|timeuntil:now}}</h5></span></td>
							<td>
								<a href="" class="btn btn-primary">Update</a>
								<a href="" class="btn btn-danger">Delete</a>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>

				<!-- Top Pagination Start -->
                {% if allbatch.has_other_pages %}
                <ul class="pagination" >
                    {% if allbatch.has_previous %}
                    <li class="page-item" ><a class="page-link" href="?page={{ allbatch.previous_page_number }}" >Previous</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                    {% endif %}
                    {% for n in allbatch.paginator.page_range %}
                        {% if allbatch.number == n %}
                            <li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{n}}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if allbatch.has_next %}
                      <li class="page-item"><a class="page-link" href="?page={{ allbatch.next_page_number}}">Next</a></li>
                    {% else %}
                      <li class="page-item disabled"><span class="page-link">Next</span></li>
                    {% endif %}
                </ul>
                {% endif %}
                <!-- Top Pagination Ends -->

			</div>
		</div>
	</div>
	<div class="col-md-3" style="text-align: center;">
		<div class="row mt-1 ml-1 mr-1">
			<div class="col" style="text-align: center; color: blue; background-color: grey;">
			</div>
		</div>
		
	</div>
</div>



{% endblock %}

templates/admintemplates/admincompanylist.html
{% extends 'admintemplates/adminmedicalbase.html' %}
{% load static %}

{% block title %}
Company List Page
{% endblock %}

{% block content %}

<div class="row mt-1 ml-1 mr-1">
	<div class="col" style="background-color: lightgreen; text-align: center;">
		<h4>Company List</h4>
	</div>
</div>

<div class="row mt-1">
	<div class="col-md-9">
		
		<div class="row ml-1 mt-1 mr-1">
			<div class="col" style="text-align: center; color: white; background-color: grey;">
				<h4>Table of Companies</h4>
			</div>
		</div>
		<div class="row mt-1">
			<div class="col-md ml-1">
				<table class="container-fluid">
					<thead>
						<tr>
							<th>SN</th>
							<th>Name</th>
							<th>Address</th>
							<th>Phone No</th>
							<th>Image</th>
							<th>Manage</th>
						</tr>
					</thead>
					<tbody>
						{% for company in allcompany %}
						<tr class="table-blog clickable-row" data-href = " {% url 'pharmacyapp:adminmedicinedetail' company.id %} ">
							<td>{{forloop.counter}}</td>
							<td>{{company.name}}</td>
							<td>{{company.address}}</td>
							<td>{{company.contact_no}}</td>
							<td><img src=" {{company.profile_image.url}}" style="width: 100%; height: mx-auto;"></td>
							<td>
								<a href="" class="btn btn-primary">Update</a>
								<a href="" class="btn btn-danger">Delete</a>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>

				<!-- Top Pagination Start -->
                {% if allcompany.has_other_pages %}
                <ul class="pagination" >
                    {% if allcompany.has_previous %}
                    <li class="page-item" ><a class="page-link" href="?page={{ allcompany.previous_page_number }}" >Previous</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                    {% endif %}
                    {% for n in allcompany.paginator.page_range %}
                        {% if allcompany.number == n %}
                            <li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{n}}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if allcompany.has_next %}
                      <li class="page-item"><a class="page-link" href="?page={{ allcompany.next_page_number}}">Next</a></li>
                    {% else %}
                      <li class="page-item disabled"><span class="page-link">Next</span></li>
                    {% endif %}
                </ul>
                {% endif %}
                <!-- Top Pagination Ends -->

			</div>
		</div>
	</div>
	<div class="col-md-3" style="text-align: center;">
		<div class="row mt-1 ml-1 mr-1">
			<div class="col" style="text-align: center; color: blue; background-color: grey;">
			</div>
		</div>
		
	</div>
</div>



{% endblock %}

templates/admintemplates/adminmedicalbase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href=" {% static 'adminstatic/css/style.css' %} ">

	<link rel="icon" href=" {% static 'adminstatic/images/s-icon.jpg' %} " sizes="96x96" >
	<script src="https://kit.fontawesome.com/469736bb45.js" crossorigin="anonymous"></script>

	<script src=" {% static 'adminstatic/js/jquery-3.4.1.min.js' %} " ></script>
	<script src=" {% static 'adminstatic/js/bootstrap.min.js' %} "></script>
	<link rel="stylesheet" type="text/css" href=" {% static 'adminstatic/css/bootstrap.min.css' %} ">

	{% block css %}
	{% endblock %}

	<link rel="stylesheet" href=" {% static 'adminstatic/css/jquery.toast.min.css' %} ">

	{% block js %}
	{% endblock %}

</head>
<body class="container-fluid" id="body">

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href=" {% url 'pharmacyapp:adminhome' %} ">Welcome-P</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href=" {% url 'pharmacyapp:adminhome' %} ">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href=" {% url 'pharmacyapp:adminmedicinelist' %} ">Medicines</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Purchase</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Sales</a>
	      </li>
	      <li class="nav-item dropdown">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          My Journal
	        </a>
	        <div class="dropdown-menu navbar-dark bg-dark" aria-labelledby="navbarDropdown">
	          <a id="navbar-dropdown" class="dropdown-item" href=" {% url 'diaryapp:diaryhome' %} " style="color: green;">Diary</a>
	          <a id="navbar-dropdown" class="dropdown-item" href=" {% url 'blogapp:bloghome' %} " style="color: green;">Blogs</a>
	          <div class="dropdown-divider"></div>
	          <a id="navbar-dropdown" class="dropdown-item" href="#" style="color: green;">To-Do-Lists</a>
	        </div>
	      </li>
	      {% if request.user.is_authenticated %}
	      <li class="nav-item">
	        <a class="nav-link disabled" href="#" style="color: #03AC13;">User: {{request.user}}</a>
	      </li>
	      <li class="nav-item">
	      	<a class="nav-link" href=" {% url 'blogapp:logout' %} " style="color: red;">Signout</a>
	      </li>
	      {% else %}
<!-- 	      <li class="nav-item">
	      	<a class="nav-link" href=" {% url 'blogapp:login' %} ">Signin</a>
	      </li>
	      <li class="nav-item">
	      	<a class="nav-link" href=" {% url 'blogapp:signup' %} ">Signup</a>
	      </li> -->
	      {% endif %}
	    </ul>
	    <form class="form-inline my-2 my-lg-0">
	      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	    </form>
	  </div>
	</nav>


	<!-- Beginning of Medical Header Attributes -->
	<div class="row mt-1 ml-1">
		<a href=" {% url 'pharmacyapp:adminmedicinelist' %} " class="btn btn-info mr-1">All-Medicine</a>
		<a href=" {% url 'pharmacyapp:adminbatchlist' %} " class="btn btn-warning mr-1">All-Batches</a>
		<a href=" {% url 'pharmacyapp:admincompanylist' %} " class="btn btn-success mr-1">Company-List</a>
		<a href=" {% url 'pharmacyapp:adminsupplierlist' %} " class="btn btn-success mr-1">Suppliers-List</a>
		<a href="" class="btn btn-danger mr-1">Expired-List</a>
	</div>

	<!-- Ending of Medical Header Attributes -->




	{% block content %}
	{% endblock %}

	<div id="footer" >
		<h4>Created By: Handsome </h4>
		
	</div>


	<script type="text/javascript" src=" {% static 'adminstatic/js/jquery.toast.min.js' %} "></script>


<script type="text/javascript">
   $(".subform1").on("submit",function(e){
      e.preventDefault();
      $this = $(this);
      $.ajax({
         type:"POST",
         url: $this.attr('action'),
         data: $this.serialize(),
         success : function(data){
            if (data.success){
                $.toast({
                    heading: 'Login Success',
                    text: data.success,
                    bgColor: 'green',
                    position: 'top-right',
                    showHideTransition: 'slide',
                    icon: 'success'
                });
                 $this.trigger("reset");
            }
            else {
              $.toast({
                    heading: 'Login Error',
                    text: data.error,
                    bgColor: 'red',
                    position: 'top-right',
                    showHideTransition: 'slide',
                    icon: 'warning'
                });
              $this.trigger("reset");
           }
         }
      });
   });
</script>


<script type="text/javascript">
   '{% if messages %}'
      '{% for message in messages %}'
         $.toast({
                 heading: 'Login Prompt',
                 text: '{{message}}',
                 bgColor: 'red',
                 position: 'top-right',
                 showHideTransition: 'slide',
                 icon: 'warning'
                });
      '{% endfor %}'
   '{% endif %}'
</script>



<script type="text/javascript">
	$(document).ready(function() {
	    $(".dropdownMenuLink").dropdown();
	});
</script>

<script type="text/javascript">
    jQuery(document).ready(function($) {
        $(".clickable-row").click(function() {
            window.location = $(this).attr("data-href");
        });
    });
</script>

</body>
</html>

templates/admintemplates/adminmedicinelist.html
{% extends 'admintemplates/adminmedicalbase.html' %}
{% load static %}

{% block title %}
Medicine List Page
{% endblock %}

{% block content %}

<div class="row mt-1 ml-1 mr-1">
	<div class="col" style="background-color: lightgreen; text-align: center;">
		<h4>Medicine List</h4>
	</div>
</div>

<div class="row mt-1">
	<div class="col-md-9">
		
		<div class="row ml-1 mt-1 mr-1">
			<div class="col" style="text-align: center; color: white; background-color: grey;">
				<h4>Table of Medicines</h4>
			</div>
		</div>
		<div class="row mt-1">
			<div class="col-md ml-1">
				<table class="container-fluid">
					<thead>
						<tr>
							<th>SN</th>
							<th>Title</th>
							<!-- <th>Medicine</th> -->
							<th>Category</th>
							<th>SKU</th>
							<th>Rack</th>
						</tr>
					</thead>
					<tbody>
						{% for medicine in allmedicines %}
						<tr class="table-blog clickable-row" data-href = " {% url 'pharmacyapp:adminmedicinedetail' medicine.id %} ">
							<td>{{forloop.counter}}</td>
							<td>{{medicine.title}}</td>
							<td>{{medicine.medicine_category}}</td>
							<td>{{medicine.sku}}</td>
							<td>{{medicine.rack}}</td>

						</tr>
						{% endfor %}
					</tbody>
				</table>

				<!-- Top Pagination Start -->
                {% if allmedicines.has_other_pages %}
                <ul class="pagination" >
                    {% if allmedicines.has_previous %}
                    <li class="page-item" ><a class="page-link" href="?page={{ allmedicines.previous_page_number }}" >Previous</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                    {% endif %}
                    {% for n in allmedicines.paginator.page_range %}
                        {% if allmedicines.number == n %}
                            <li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{n}}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if allmedicines.has_next %}
                      <li class="page-item"><a class="page-link" href="?page={{ allmedicines.next_page_number}}">Next</a></li>
                    {% else %}
                      <li class="page-item disabled"><span class="page-link">Next</span></li>
                    {% endif %}
                </ul>
                {% endif %}
                <!-- Top Pagination Ends -->

			</div>
		</div>
	</div>
	<div class="col-md-3" style="text-align: center;">
		<div class="row mt-1 ml-1 mr-1">
			<div class="col" style="text-align: center; color: blue; background-color: grey;">
				<h4>Expired Medicines</h4>
			</div>
		</div>
		<div class="row mt-1">
			<div class="col-md">
				<table class="container-fluid">
					<thead>
						<tr>
							<th>SN</th>
							<th>Name</th>
							<!-- <th>Medicine</th> -->
							<!-- <th>Category</th> -->
							<th>Batch</th>
							<!-- <th>Quantity</th> -->
							<!-- <th>Cost Price</th> -->
							<!-- <th>Selling Price</th> -->
							<th>Expiry Date</th>
							<!-- <th>Time-to-expiry</th> -->
						</tr>
					</thead>
					<tbody>
						{% for medicine in expired_medicine %}
						<tr class="table-expire clickable-row" data-href=" {% url 'pharmacyapp:adminsinglemedicinedetail' medicine.id %} ">
							<td>{{forloop.counter}}</td>
							<td>{{medicine.title}}</td>
<!-- 							<td>{{medicine.medicine}}</td>
							<td>{{medicine.medicine_category}}</td> -->
							<td>{{medicine.batch}}</td>
							<!-- <td>{{medicine.quantity}}</td> -->
							<!-- <td>{{medicine.cost_price}}</td> -->
							<!-- <td>{{medicine.selling_price}}</td> -->
							<td>{{medicine.batch.expire_date}}</td>
							<!-- <td>{{medicine.batch.expire_date}}</td> -->
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
		</div>
	</div>
</div>



{% endblock %}

templates/admintemplates/adminsupplierlist.html
{% extends 'admintemplates/adminmedicalbase.html' %}
{% load static %}

{% block title %}
Supplier List Page
{% endblock %}

{% block content %}

<div class="row mt-1 ml-1 mr-1">
	<div class="col" style="background-color: lightgreen; text-align: center;">
		<h4>Supplier List</h4>
	</div>
</div>

<div class="row mt-1">
	<div class="col-md-9">
		
		<div class="row ml-1 mt-1 mr-1">
			<div class="col" style="text-align: center; color: white; background-color: grey;">
				<h4>Table of Suppliers</h4>
			</div>
		</div>
		<div class="row mt-1">
			<div class="col-md ml-1">
				<table class="container-fluid">
					<thead>
						<tr>
							<th>SN</th>
							<th>Name</th>
							<th>Phone No</th>
							<th>Manage</th>
						</tr>
					</thead>
					<tbody>
						{% for supplier in allsupplier %}
						<tr class="table-blog clickable-row" data-href = " {% url 'pharmacyapp:adminmedicinedetail' supplier.id %} ">
							<td>{{forloop.counter}}</td>
							<td>{{supplier.name}}</td>
							<td>{{supplier.contact_no}}</td>
							<td>
								<a href="" class="btn btn-primary">Update</a>
								<a href="" class="btn btn-danger">Delete</a>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>

				<!-- Top Pagination Start -->
                {% if allsupplier.has_other_pages %}
                <ul class="pagination" >
                    {% if allsupplier.has_previous %}
                    <li class="page-item" ><a class="page-link" href="?page={{ allsupplier.previous_page_number }}" >Previous</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                    {% endif %}
                    {% for n in allsupplier.paginator.page_range %}
                        {% if allsupplier.number == n %}
                            <li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{n}}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if allsupplier.has_next %}
                      <li class="page-item"><a class="page-link" href="?page={{ allsupplier.next_page_number}}">Next</a></li>
                    {% else %}
                      <li class="page-item disabled"><span class="page-link">Next</span></li>
                    {% endif %}
                </ul>
                {% endif %}
                <!-- Top Pagination Ends -->

			</div>
		</div>
	</div>
	<div class="col-md-3" style="text-align: center;">
		<div class="row mt-1 ml-1 mr-1">
			<div class="col" style="text-align: center; color: blue; background-color: grey;">
			</div>
		</div>
		
	</div>
</div>



{% endblock %}